export const INIT_TODOS = 'INIT_TODOS'
export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const TOGGLE_TODO = 'TOGGLE_TODO'
export const EDIT_TITLE = 'CHANGE_TITLE'
export const TOGGLE_ALL = 'TOGGLE_ALL'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
